//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Api.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_centro_costo_sub_centro_costo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ct_centro_costo_sub_centro_costo()
        {
            this.tbl_subcentro = new HashSet<tbl_subcentro>();
            this.tbl_usuario_x_subcentro = new HashSet<tbl_usuario_x_subcentro>();
        }
    
        public int IdEmpresa { get; set; }
        public string IdCentroCosto { get; set; }
        public string IdCentroCosto_sub_centro_costo { get; set; }
        public string cod_subcentroCosto { get; set; }
        public string Centro_costo { get; set; }
        public string pc_Estado { get; set; }
        public string IdCtaCble { get; set; }
    
        public virtual ct_centro_costo ct_centro_costo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_subcentro> tbl_subcentro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_usuario_x_subcentro> tbl_usuario_x_subcentro { get; set; }
    }
}
