//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Api.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities_general : DbContext
    {
        public Entities_general()
            : base("name=Entities_general")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ct_centro_costo> ct_centro_costo { get; set; }
        public virtual DbSet<ct_centro_costo_sub_centro_costo> ct_centro_costo_sub_centro_costo { get; set; }
        public virtual DbSet<in_Producto> in_Producto { get; set; }
        public virtual DbSet<in_UnidadMedida> in_UnidadMedida { get; set; }
        public virtual DbSet<tb_bodega> tb_bodega { get; set; }
        public virtual DbSet<tb_empresa> tb_empresa { get; set; }
        public virtual DbSet<tb_sucursal> tb_sucursal { get; set; }
        public virtual DbSet<tbl_bodega> tbl_bodega { get; set; }
        public virtual DbSet<tbl_producto> tbl_producto { get; set; }
        public virtual DbSet<tbl_subcentro> tbl_subcentro { get; set; }
        public virtual DbSet<tbl_usuario> tbl_usuario { get; set; }
        public virtual DbSet<tbl_usuario_x_bodega> tbl_usuario_x_bodega { get; set; }
        public virtual DbSet<tbl_usuario_x_subcentro> tbl_usuario_x_subcentro { get; set; }
        public virtual DbSet<in_UnidadMedida_Equiv_conversion> in_UnidadMedida_Equiv_conversion { get; set; }
        public virtual DbSet<tbl_movimientos> tbl_movimientos { get; set; }
        public virtual DbSet<tbl_sincronizacion_turno> tbl_sincronizacion_turno { get; set; }
        public virtual DbSet<in_linea> in_linea { get; set; }
        public virtual DbSet<tbl_movimientos_det> tbl_movimientos_det { get; set; }
        public virtual DbSet<tbl_producto_x_tbl_bodega> tbl_producto_x_tbl_bodega { get; set; }
    
        public virtual int sp_revisar_estados_oc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_revisar_estados_oc");
        }
    
        public virtual ObjectResult<sp_stock_Result> sp_stock(string idUsuario)
        {
            var idUsuarioParameter = idUsuario != null ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_stock_Result>("sp_stock", idUsuarioParameter);
        }
    
        public virtual ObjectResult<sp_get_consumo_semanal_Result> sp_get_consumo_semanal(string idUsuario)
        {
            var idUsuarioParameter = idUsuario != null ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_consumo_semanal_Result>("sp_get_consumo_semanal", idUsuarioParameter);
        }
    
        public virtual ObjectResult<sp_oc_x_aprobar_Result> sp_oc_x_aprobar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_oc_x_aprobar_Result>("sp_oc_x_aprobar");
        }
    }
}
