//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Api.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_producto
    {
        public int IdEmpresaSCI { get; set; }
        public decimal IdSCI { get; set; }
        public int IdEmpresa { get; set; }
        public decimal IdProducto { get; set; }
    
        public virtual in_Producto in_Producto { get; set; }
    }
}
